# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Hostify Runner

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '* 4 * * *'

permissions:
  contents: write

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Chrome
      # You may pin to the exact commit or the version.
      # uses: browser-actions/setup-chrome@4fa655aad48f56911cad16db9252399a9e592848
      uses: browser-actions/setup-chrome@v0.0.0
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: setup-chromedriver
      # You may pin to the exact commit or the version.
      # uses: nanasess/setup-chromedriver@da249190822b1cd9bd78038fbadf65fa9b9f9c24
      uses: nanasess/setup-chromedriver@v1.0.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: installing Telebot
      run: |
        pip install pytelegrambotapi
    - name: Installing Requirements
      run: |
        pip install -r requirements.txt
    - name: Running The Bot
      run: |
        python .github/workflows/Hostify/run.py
